### ISSUE TITLE
meta_key and meta_query

### ISSUE THREAD

**Issue by sboisvert** [alleyinteractive/es-wp-query#29]
When both parameters are present only meta_key is used, the meta_query part is silently dropped.
The current WP_Query behaviour is to have an exist check on the meta_key that is inside the meta_key property as well as what is defined into meta_query.

Let me know if you think this should be supported and I'll write a patch.

**Comment by sboisvert** [comment]
(just a note, I think meta_key might need to be defined when doing orderby 'meta_value_num' to determine which meta_value to use when sorting.)

**Comment by mboynes** [comment]
A patch would be much appreciated :+1:. The meta query might need a larger update to bring it up to speed with the latest in core, so if it seems like this is easier said than done and starts to turn into that, let me know and we can collaborate on the larger overhaul.

**Comment by mboynes** [comment]
Quick update here: I'm currently working on this issue and am hoping to have a PR ready today or tomorrow

**Comment by mboynes** [comment]
@sboisvert can you (or someone on your team) code review that? ^

**Comment by sboisvert** [comment]
Looks good by me. @philipjohn Do you have any concerns with putting this as the RC release on production?

**Comment by mboynes** [comment]
None at all. Thanks!

**Comment by mboynes** [comment]
After speaking with @gibrown and @xyu, we decided to create multiple versions of ES_WP_Query to support different ES versions (See #37). @sboisvert, VIP will need to use the `master-1.x` branch (I'll make it an official release once I get #35 and #36 merged).

**Comment by philipjohn** [comment]
Yep, let's make this our RC.

**Comment by sboisvert** [comment]
Okay pulling master 1.x and pushing it to RC plugins
