### ISSUE TITLE
is_main_query() returns false

### ISSUE THREAD

**Issue by sboisvert** [alleyinteractive/es-wp-query#38]
I'm not sure if this falls under a bug or a feature, but if you do `$query->is_main_query()` inside the 
`do_action_ref_array( 'pre_get_posts', array( &$this ) );` hook this will return false for the "shadow" ES query of the main query. While I understand that it's technically true that this is not the real main WP_Query object I feel like it should return true.

Thoughts?

**Comment by rebeccahum** [comment]
After lots of keyboard-head-smashing, I've stumbled upon this and that explains why `is_main_query()` is not working as expected.
